// lib/exports/performance/gatling.ts
export function exportToGatling(testCases: any[], suiteName: string) {
  const className = suiteName.replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    `package simulations`,
    ``,
    `import io.gatling.core.Predef._`,
    `import io.gatling.http.Predef._`,
    `import scala.concurrent.duration._`,
    ``,
    `/**`,
    ` * ${suiteName}`,
    ` * Generated by SynthQA`,
    ` */`,
    `class ${className}Simulation extends Simulation {`,
    ``,
    `  val httpProtocol = http`,
    `    .baseUrl("https://example.com")`,
    `    .acceptHeader("application/json")`,
    `    .userAgentHeader("Gatling/SynthQA")`,
    ``,
    `  val scn = scenario("${suiteName}")`,
  ];

  testCases.forEach((tc, idx) => {
    if (idx > 0) lines[lines.length - 1] += "";

    lines.push(`    .exec(http("${tc.title || `Request ${idx + 1}`}")`);
    lines.push(`      .get("/")`);
    lines.push(`      .check(status.is(200)))`);
    lines.push(`    .pause(1)`);
  });

  lines.push(``);
  lines.push(`  setUp(`);
  lines.push(`    scn.inject(rampUsers(10).during(10.seconds))`);
  lines.push(`  ).protocols(httpProtocol)`);
  lines.push(`   .assertions(`);
  lines.push(`     global.responseTime.max.lt(5000),`);
  lines.push(`     global.successfulRequests.percent.gt(95)`);
  lines.push(`   )`);
  lines.push(`}`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${className}Simulation.scala`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/x-scala",
  };
}
