// lib/exports/performance/jmeter.ts
export function exportToJMeter(testCases: any[], suiteName: string) {
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.5">\n`;
  xml += `  <hashTree>\n`;
  xml += `    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="${suiteName}" enabled="true">\n`;
  xml += `      <stringProp name="TestPlan.comments">Generated by SynthQA</stringProp>\n`;
  xml += `      <boolProp name="TestPlan.functional_mode">false</boolProp>\n`;
  xml += `      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>\n`;
  xml += `      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments">\n`;
  xml += `        <collectionProp name="Arguments.arguments">\n`;
  xml += `          <elementProp name="BASE_URL" elementType="Argument">\n`;
  xml += `            <stringProp name="Argument.name">BASE_URL</stringProp>\n`;
  xml += `            <stringProp name="Argument.value">https://example.com</stringProp>\n`;
  xml += `          </elementProp>\n`;
  xml += `        </collectionProp>\n`;
  xml += `      </elementProp>\n`;
  xml += `    </TestPlan>\n`;
  xml += `    <hashTree>\n`;

  // Thread Group
  xml += `      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Users" enabled="true">\n`;
  xml += `        <stringProp name="ThreadGroup.num_threads">10</stringProp>\n`;
  xml += `        <stringProp name="ThreadGroup.ramp_time">1</stringProp>\n`;
  xml += `        <longProp name="ThreadGroup.duration">60</longProp>\n`;
  xml += `        <stringProp name="ThreadGroup.delay">0</stringProp>\n`;
  xml += `        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>\n`;
  xml += `      </ThreadGroup>\n`;
  xml += `      <hashTree>\n`;

  testCases.forEach((tc, idx) => {
    xml += `        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="${tc.title || `Request ${idx + 1}`}" enabled="true">\n`;
    xml += `          <elementProp name="HTTPsampler.Arguments" elementType="Arguments">\n`;
    xml += `            <collectionProp name="Arguments.arguments"/>\n`;
    xml += `          </elementProp>\n`;
    xml += `          <stringProp name="HTTPSampler.domain">\${BASE_URL}</stringProp>\n`;
    xml += `          <stringProp name="HTTPSampler.path">/</stringProp>\n`;
    xml += `          <stringProp name="HTTPSampler.method">GET</stringProp>\n`;
    xml += `          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>\n`;
    xml += `          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>\n`;
    xml += `          <stringProp name="HTTPSampler.comments">${tc.description || ""}</stringProp>\n`;
    xml += `        </HTTPSamplerProxy>\n`;
    xml += `        <hashTree/>\n`;
  });

  // Add listeners
  xml += `        <ResultCollector guiclass="ViewResultsFullVisualizer" testclass="ResultCollector" testname="View Results Tree" enabled="true"/>\n`;
  xml += `        <hashTree/>\n`;
  xml += `        <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report" enabled="true"/>\n`;
  xml += `        <hashTree/>\n`;

  xml += `      </hashTree>\n`;
  xml += `    </hashTree>\n`;
  xml += `  </hashTree>\n`;
  xml += `</jmeterTestPlan>`;

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-${timestamp}.jmx`;

  return {
    content: xml,
    filename,
    mimeType: "application/xml",
  };
}
