// lib/exports/performance/k6.ts
export function exportToK6(testCases: any[], suiteName: string) {
  const lines = [
    `import http from 'k6/http';`,
    `import { check, sleep } from 'k6';`,
    `import { Rate } from 'k6/metrics';`,
    ``,
    `/**`,
    ` * ${suiteName}`,
    ` * Generated by SynthQA`,
    ` */`,
    ``,
    `// Custom metrics`,
    `const errorRate = new Rate('errors');`,
    ``,
    `// Test configuration`,
    `export const options = {`,
    `  vus: 10, // Virtual users`,
    `  duration: '30s',`,
    `  thresholds: {`,
    `    http_req_duration: ['p(95)<500'], // 95% of requests must complete below 500ms`,
    `    errors: ['rate<0.1'], // Error rate must be below 10%`,
    `  },`,
    `};`,
    ``,
    `const BASE_URL = __ENV.BASE_URL || 'https://example.com';`,
    ``,
    `export default function () {`,
  ];

  testCases.forEach((tc, idx) => {
    lines.push(`  // Test ${idx + 1}: ${tc.title}`);
    if (tc.description) {
      lines.push(`  // ${tc.description}`);
    }

    lines.push(`  {`);
    lines.push(`    const response = http.get(\`\${BASE_URL}/\`);`);
    lines.push(`    check(response, {`);
    lines.push(`      'status is 200': (r) => r.status === 200,`);
    lines.push(
      `      'response time < 500ms': (r) => r.timings.duration < 500,`,
    );
    lines.push(`    }) || errorRate.add(1);`);
    lines.push(`  }`);
    lines.push(``);
  });

  lines.push(`  sleep(1);`);
  lines.push(`}`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-${timestamp}.js`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/javascript",
  };
}
