// lib/exports/performance/locust.ts
export function exportToLocust(testCases: any[], suiteName: string) {
  const className = suiteName.replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    `"""`,
    `${suiteName} - Locust Load Test`,
    `Generated by SynthQA`,
    ``,
    `Run with: locust -f ${className.toLowerCase()}_locustfile.py --host=https://example.com`,
    `"""`,
    ``,
    `from locust import HttpUser, task, between`,
    `import json`,
    ``,
    ``,
    `class ${className}User(HttpUser):`,
    `    """Load test user for ${suiteName}"""`,
    `    `,
    `    # Wait between 1 and 3 seconds between tasks`,
    `    wait_time = between(1, 3)`,
    `    `,
    `    def on_start(self):`,
    `        """Called when a simulated user starts"""`,
    `        # Add authentication/setup here if needed`,
    `        pass`,
    `    `,
  ];

  testCases.forEach((tc, idx) => {
    const taskName = tc.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");

    // Assign weight based on priority
    const weight =
      tc.priority === "critical"
        ? 5
        : tc.priority === "high"
          ? 3
          : tc.priority === "medium"
            ? 2
            : 1;

    lines.push(`    @task(${weight})`);
    lines.push(`    def ${taskName}(self):`);
    lines.push(`        """`);
    lines.push(`        ${tc.title}`);
    if (tc.description) {
      lines.push(`        ${tc.description}`);
    }
    lines.push(`        """`);

    // Generate request based on test case
    if (tc.steps && Array.isArray(tc.steps)) {
      const firstStep = tc.steps[0] || "";

      if (firstStep.toLowerCase().includes("post")) {
        lines.push(`        headers = {"Content-Type": "application/json"}`);
        lines.push(`        payload = {`);
        lines.push(`            "test": "data"`);
        lines.push(`        }`);
        lines.push(
          `        with self.client.post("/endpoint", json=payload, headers=headers, catch_response=True) as response:`,
        );
        lines.push(`            if response.status_code == 200:`);
        lines.push(`                response.success()`);
        lines.push(`            else:`);
        lines.push(
          `                response.failure(f"Got status code {response.status_code}")`,
        );
      } else if (firstStep.toLowerCase().includes("put")) {
        lines.push(`        headers = {"Content-Type": "application/json"}`);
        lines.push(`        payload = {"test": "data"}`);
        lines.push(
          `        with self.client.put("/endpoint/1", json=payload, headers=headers, catch_response=True) as response:`,
        );
        lines.push(`            if response.status_code in [200, 204]:`);
        lines.push(`                response.success()`);
        lines.push(`            else:`);
        lines.push(
          `                response.failure(f"Got status code {response.status_code}")`,
        );
      } else {
        // Default to GET
        lines.push(
          `        with self.client.get("/endpoint", catch_response=True) as response:`,
        );
        lines.push(`            if response.status_code == 200:`);
        lines.push(`                response.success()`);
        lines.push(`            else:`);
        lines.push(
          `                response.failure(f"Got status code {response.status_code}")`,
        );
      }
    } else {
      lines.push(`        # Default GET request`);
      lines.push(`        self.client.get("/")`);
    }

    lines.push(`    `);
  });

  lines.push(``);
  lines.push(`# Run configuration (optional)`);
  lines.push(`# Configure via CLI or web UI at http://localhost:8089`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${className.toLowerCase()}_locustfile_${timestamp}.py`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/x-python",
  };
}
