// lib/exports/web/cypress.ts
export function exportToCypress(testCases: any[], suiteName: string) {
  const lines = [
    `/**`,
    ` * ${suiteName}`,
    ` * Generated by SynthQA`,
    ` */`,
    ``,
    `describe('${suiteName}', () => {`,
    `  const baseUrl = Cypress.config('baseUrl') || 'https://example.com';`,
    ``,
    `  beforeEach(() => {`,
    `    // Run before each test`,
    `    cy.visit('/');`,
    `  });`,
    ``,
  ];

  testCases.forEach((tc, idx) => {
    const testName = tc.title || `Test ${idx + 1}`;

    lines.push(`  it('${testName}', () => {`);

    if (tc.description) {
      lines.push(`    // ${tc.description}`);
      lines.push(``);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`    // Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`    // - ${p}`);
      });
      lines.push(``);
    }

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(`    // Step ${stepIdx + 1}: ${step}`);

        // Generate Cypress commands
        if (
          step.toLowerCase().includes("visit") ||
          step.toLowerCase().includes("navigate")
        ) {
          lines.push(`    cy.visit('/page');`);
        } else if (step.toLowerCase().includes("click")) {
          lines.push(`    cy.get('#elementId').click();`);
        } else if (
          step.toLowerCase().includes("type") ||
          step.toLowerCase().includes("enter")
        ) {
          lines.push(`    cy.get('#inputId').type('test value');`);
        } else if (step.toLowerCase().includes("select")) {
          lines.push(`    cy.get('#selectId').select('option');`);
        } else if (step.toLowerCase().includes("wait")) {
          lines.push(`    cy.get('#elementId').should('be.visible');`);
        } else {
          lines.push(`    // TODO: Implement - ${step}`);
        }
        lines.push(``);
      });
    }

    // Expected results
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(`    // Expected results:`);
      tc.expected_results.forEach((result: string) => {
        lines.push(`    // - ${result}`);

        if (
          result.toLowerCase().includes("visible") ||
          result.toLowerCase().includes("displayed")
        ) {
          lines.push(`    cy.get('#elementId').should('be.visible');`);
        } else if (
          result.toLowerCase().includes("text") ||
          result.toLowerCase().includes("contain")
        ) {
          lines.push(
            `    cy.get('#elementId').should('contain', 'expected text');`,
          );
        } else {
          lines.push(`    // TODO: Add assertion`);
        }
      });
    }

    lines.push(`  });`);
    lines.push(``);
  });

  lines.push(`});`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-${timestamp}.cy.js`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/javascript",
  };
}
