// lib/exports/web/playwright.ts
export function exportToPlaywright(testCases: any[], suiteName: string) {
  const lines = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `/**`,
    ` * ${suiteName}`,
    ` * Generated by SynthQA`,
    ` */`,
    ``,
    `test.describe('${suiteName}', () => {`,
    `  // Configuration`,
    `  const baseURL = 'https://example.com'; // Update with your URL`,
    ``,
    `  test.beforeEach(async ({ page }) => {`,
    `    // Set up before each test`,
    `    await page.goto(baseURL);`,
    `  });`,
    ``,
  ];

  testCases.forEach((tc, idx) => {
    const testName = tc.title || `Test ${idx + 1}`;

    lines.push(`  test('${testName}', async ({ page }) => {`);

    if (tc.description) {
      lines.push(`    // ${tc.description}`);
      lines.push(``);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`    // Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`    // - ${p}`);
      });
      lines.push(``);
    }

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(`    // Step ${stepIdx + 1}: ${step}`);

        // Generate Playwright code based on step
        if (
          step.toLowerCase().includes("navigate") ||
          step.toLowerCase().includes("go to")
        ) {
          lines.push(`    await page.goto('/page');`);
        } else if (step.toLowerCase().includes("click")) {
          lines.push(`    await page.click('#elementId');`);
        } else if (
          step.toLowerCase().includes("fill") ||
          step.toLowerCase().includes("enter")
        ) {
          lines.push(`    await page.fill('#inputId', 'test value');`);
        } else if (step.toLowerCase().includes("select")) {
          lines.push(`    await page.selectOption('#selectId', 'value');`);
        } else if (step.toLowerCase().includes("wait")) {
          lines.push(`    await page.waitForSelector('#elementId');`);
        } else {
          lines.push(`    // TODO: Implement - ${step}`);
        }
        lines.push(``);
      });
    }

    // Expected results
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(`    // Expected results:`);
      tc.expected_results.forEach((result: string, resIdx: number) => {
        lines.push(`    // ${resIdx + 1}. ${result}`);

        // Generate basic assertions
        if (
          result.toLowerCase().includes("visible") ||
          result.toLowerCase().includes("displayed")
        ) {
          lines.push(
            `    await expect(page.locator('#elementId')).toBeVisible();`,
          );
        } else if (
          result.toLowerCase().includes("text") ||
          result.toLowerCase().includes("contains")
        ) {
          lines.push(
            `    await expect(page.locator('#elementId')).toContainText('expected text');`,
          );
        } else {
          lines.push(`    // TODO: Add assertion for - ${result}`);
        }
      });
    }

    lines.push(`  });`);
    lines.push(``);
  });

  lines.push(`});`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-${timestamp}.spec.ts`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/typescript",
  };
}
