// lib/exports/web/selenium.ts
export function exportToSelenium(testCases: any[], suiteName: string) {
  const className = suiteName.replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    `"""`,
    `${suiteName} - Selenium Test Suite`,
    `Generated by SynthQA`,
    `"""`,
    ``,
    `import unittest`,
    `from selenium import webdriver`,
    `from selenium.webdriver.common.by import By`,
    `from selenium.webdriver.support.ui import WebDriverWait`,
    `from selenium.webdriver.support import expected_conditions as EC`,
    `from selenium.common.exceptions import TimeoutException`,
    ``,
    ``,
    `class Test${className}(unittest.TestCase):`,
    `    """Test suite for ${suiteName}"""`,
    ``,
    `    def setUp(self):`,
    `        """Set up test fixtures"""`,
    `        self.driver = webdriver.Chrome()`,
    `        self.driver.implicitly_wait(10)`,
    `        self.base_url = "https://example.com"  # Update with your URL`,
    ``,
    `    def tearDown(self):`,
    `        """Tear down test fixtures"""`,
    `        self.driver.quit()`,
    ``,
  ];

  testCases.forEach((tc, idx) => {
    const methodName = tc.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");

    lines.push(`    def test_${idx + 1}_${methodName}(self):`);
    lines.push(`        """${tc.title}"""`);

    if (tc.description) {
      lines.push(`        # ${tc.description}`);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`        # Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`        # - ${p}`);
      });
    }

    lines.push(``);
    lines.push(`        driver = self.driver`);
    lines.push(``);

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(`        # Step ${stepIdx + 1}: ${step}`);

        // Generate basic Selenium code based on step content
        if (
          step.toLowerCase().includes("navigate") ||
          step.toLowerCase().includes("open")
        ) {
          lines.push(`        driver.get(self.base_url + "/page")`);
        } else if (step.toLowerCase().includes("click")) {
          lines.push(
            `        element = driver.find_element(By.ID, "element_id")`,
          );
          lines.push(`        element.click()`);
        } else if (
          step.toLowerCase().includes("enter") ||
          step.toLowerCase().includes("type")
        ) {
          lines.push(
            `        element = driver.find_element(By.NAME, "input_name")`,
          );
          lines.push(`        element.send_keys("test value")`);
        } else if (
          step.toLowerCase().includes("verify") ||
          step.toLowerCase().includes("check")
        ) {
          lines.push(
            `        element = driver.find_element(By.CLASS_NAME, "element_class")`,
          );
          lines.push(`        self.assertTrue(element.is_displayed())`);
        } else {
          lines.push(`        # TODO: Implement - ${step}`);
          lines.push(`        pass`);
        }
        lines.push(``);
      });
    }

    // Expected results as assertions
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(`        # Expected results:`);
      tc.expected_results.forEach((result: string) => {
        lines.push(`        # - ${result}`);
      });
      lines.push(`        # Add appropriate assertions here`);
    }

    lines.push(``);
  });

  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    unittest.main()`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `test_${suiteName.toLowerCase().replace(/\s+/g, "_")}_${timestamp}.py`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/x-python",
  };
}
