// lib/exports/mobile/appium.ts
export function exportToAppium(testCases: any[], suiteName: string) {
  const className = suiteName.replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    `"""`,
    `${suiteName} - Appium Test Suite`,
    `Generated by SynthQA`,
    `"""`,
    ``,
    `import unittest`,
    `from appium import webdriver`,
    `from appium.webdriver.common.appiumby import AppiumBy`,
    `from selenium.webdriver.support.ui import WebDriverWait`,
    `from selenium.webdriver.support import expected_conditions as EC`,
    ``,
    ``,
    `class Test${className}(unittest.TestCase):`,
    `    """Mobile test suite for ${suiteName}"""`,
    ``,
    `    def setUp(self):`,
    `        """Set up test fixtures"""`,
    `        desired_caps = {`,
    `            'platformName': 'Android',  # or 'iOS'`,
    `            'platformVersion': '12.0',`,
    `            'deviceName': 'Android Emulator',`,
    `            'app': '/path/to/your/app.apk',  # or .ipa for iOS`,
    `            'automationName': 'UiAutomator2',  # or 'XCUITest' for iOS`,
    `            'newCommandTimeout': 300`,
    `        }`,
    `        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)`,
    `        self.driver.implicitly_wait(10)`,
    ``,
    `    def tearDown(self):`,
    `        """Tear down test fixtures"""`,
    `        self.driver.quit()`,
    ``,
  ];

  testCases.forEach((tc, idx) => {
    const methodName = tc.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");

    lines.push(`    def test_${idx + 1}_${methodName}(self):`);
    lines.push(`        """${tc.title}"""`);

    if (tc.description) {
      lines.push(`        # ${tc.description}`);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`        # Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`        # - ${p}`);
      });
    }

    lines.push(``);
    lines.push(`        driver = self.driver`);
    lines.push(``);

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(`        # Step ${stepIdx + 1}: ${step}`);

        // Generate Appium code based on step content
        if (
          step.toLowerCase().includes("tap") ||
          step.toLowerCase().includes("click")
        ) {
          lines.push(
            `        element = driver.find_element(AppiumBy.ID, "element_id")`,
          );
          lines.push(`        element.click()`);
        } else if (step.toLowerCase().includes("swipe")) {
          lines.push(
            `        driver.swipe(start_x=100, start_y=500, end_x=100, end_y=100, duration=800)`,
          );
        } else if (
          step.toLowerCase().includes("type") ||
          step.toLowerCase().includes("enter")
        ) {
          lines.push(
            `        element = driver.find_element(AppiumBy.ACCESSIBILITY_ID, "input_field")`,
          );
          lines.push(`        element.send_keys("test value")`);
        } else if (step.toLowerCase().includes("scroll")) {
          lines.push(
            `        driver.find_element(AppiumBy.ANDROID_UIAUTOMATOR,`,
          );
          lines.push(
            `            'new UiScrollable(new UiSelector().scrollable(true)).scrollToEnd(10)')`,
          );
        } else if (
          step.toLowerCase().includes("verify") ||
          step.toLowerCase().includes("check")
        ) {
          lines.push(
            `        element = driver.find_element(AppiumBy.XPATH, "//android.widget.TextView[@text='Expected Text']")`,
          );
          lines.push(`        self.assertTrue(element.is_displayed())`);
        } else if (step.toLowerCase().includes("wait")) {
          lines.push(`        WebDriverWait(driver, 10).until(`);
          lines.push(
            `            EC.presence_of_element_located((AppiumBy.ID, "element_id"))`,
          );
          lines.push(`        )`);
        } else {
          lines.push(`        # TODO: Implement - ${step}`);
          lines.push(`        pass`);
        }
        lines.push(``);
      });
    }

    // Expected results
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(`        # Expected results:`);
      tc.expected_results.forEach((result: string) => {
        lines.push(`        # - ${result}`);
      });
      lines.push(`        # Add appropriate assertions here`);
    }

    lines.push(``);
  });

  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    unittest.main()`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `test_${suiteName.toLowerCase().replace(/\s+/g, "_")}_${timestamp}.py`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/x-python",
  };
}
