// lib/exports/mobile/espresso.ts
export function exportToEspresso(testCases: any[], suiteName: string) {
  const className = suiteName.replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    `package com.example.tests`,
    ``,
    `import androidx.test.espresso.Espresso.onView`,
    `import androidx.test.espresso.action.ViewActions.*`,
    `import androidx.test.espresso.assertion.ViewAssertions.*`,
    `import androidx.test.espresso.matcher.ViewMatchers.*`,
    `import androidx.test.ext.junit.rules.ActivityScenarioRule`,
    `import androidx.test.ext.junit.runners.AndroidJUnit4`,
    `import org.junit.Rule`,
    `import org.junit.Test`,
    `import org.junit.runner.RunWith`,
    ``,
    `/**`,
    ` * ${suiteName}`,
    ` * Generated by SynthQA`,
    ` */`,
    `@RunWith(AndroidJUnit4::class)`,
    `class ${className}Test {`,
    ``,
    `    @get:Rule`,
    `    val activityRule = ActivityScenarioRule(MainActivity::class.java)`,
    ``,
  ];

  testCases.forEach((tc, idx) => {
    const methodName = tc.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");

    lines.push(`    @Test`);
    lines.push(`    fun test_${methodName}() {`);
    lines.push(`        // ${tc.title}`);

    if (tc.description) {
      lines.push(`        // ${tc.description}`);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`        // Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`        // - ${p}`);
      });
    }

    lines.push(``);

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(`        // Step ${stepIdx + 1}: ${step}`);

        if (
          step.toLowerCase().includes("click") ||
          step.toLowerCase().includes("tap")
        ) {
          lines.push(`        onView(withId(R.id.button_id)).perform(click())`);
        } else if (
          step.toLowerCase().includes("type") ||
          step.toLowerCase().includes("enter")
        ) {
          lines.push(`        onView(withId(R.id.edit_text_id))`);
          lines.push(
            `            .perform(typeText("test value"), closeSoftKeyboard())`,
          );
        } else if (step.toLowerCase().includes("swipe")) {
          lines.push(`        onView(withId(R.id.view_id)).perform(swipeUp())`);
        } else if (step.toLowerCase().includes("scroll")) {
          lines.push(
            `        onView(withId(R.id.scroll_view_id)).perform(scrollTo())`,
          );
        } else {
          lines.push(`        // TODO: Implement - ${step}`);
        }
        lines.push(``);
      });
    }

    // Expected results
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(`        // Expected results:`);
      tc.expected_results.forEach((result: string) => {
        lines.push(`        // - ${result}`);
        if (
          result.toLowerCase().includes("visible") ||
          result.toLowerCase().includes("displayed")
        ) {
          lines.push(
            `        onView(withId(R.id.element_id)).check(matches(isDisplayed()))`,
          );
        } else if (result.toLowerCase().includes("text")) {
          lines.push(
            `        onView(withId(R.id.text_view_id)).check(matches(withText("Expected Text")))`,
          );
        }
      });
    }

    lines.push(`    }`);
    lines.push(``);
  });

  lines.push(`}`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${className}Test.kt`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/x-kotlin",
  };
}
