// lib/exports/mobile/maestro.ts
export function exportToMaestro(testCases: any[], suiteName: string) {
  const lines = [
    `# ${suiteName}`,
    `# Generated by SynthQA`,
    `# Run with: maestro test flow.yaml`,
    ``,
    `appId: com.example.app  # Update with your app bundle ID`,
    ``,
    `---`,
  ];

  testCases.forEach((tc, idx) => {
    lines.push(``);
    lines.push(`# Test ${idx + 1}: ${tc.title}`);
    if (tc.description) {
      lines.push(`# ${tc.description}`);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`# Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`#   - ${p}`);
      });
    }

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(``);
        lines.push(`# Step ${stepIdx + 1}: ${step}`);

        // Generate Maestro YAML commands
        if (
          step.toLowerCase().includes("launch") ||
          step.toLowerCase().includes("open")
        ) {
          lines.push(`- launchApp`);
        } else if (
          step.toLowerCase().includes("tap") ||
          step.toLowerCase().includes("click")
        ) {
          if (step.toLowerCase().includes("button")) {
            lines.push(`- tapOn: "Button Text"`);
          } else {
            lines.push(`- tapOn:`);
            lines.push(`    id: "element_id"`);
          }
        } else if (
          step.toLowerCase().includes("type") ||
          step.toLowerCase().includes("enter")
        ) {
          lines.push(`- tapOn: "Input Field"`);
          lines.push(`- inputText: "test value"`);
        } else if (step.toLowerCase().includes("swipe")) {
          if (step.toLowerCase().includes("up")) {
            lines.push(`- swipe:`);
            lines.push(`    direction: UP`);
          } else if (step.toLowerCase().includes("down")) {
            lines.push(`- swipe:`);
            lines.push(`    direction: DOWN`);
          } else {
            lines.push(`- swipe:`);
            lines.push(`    direction: LEFT`);
          }
        } else if (step.toLowerCase().includes("scroll")) {
          lines.push(`- scroll`);
        } else if (step.toLowerCase().includes("wait")) {
          lines.push(`- waitForAnimationToEnd`);
        } else if (
          step.toLowerCase().includes("verify") ||
          step.toLowerCase().includes("assert")
        ) {
          lines.push(`- assertVisible: "Expected Text"`);
        } else if (step.toLowerCase().includes("back")) {
          lines.push(`- back`);
        } else {
          lines.push(`# TODO: Implement - ${step}`);
        }
      });
    }

    // Expected results
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(``);
      lines.push(`# Expected results:`);
      tc.expected_results.forEach((result: string) => {
        lines.push(`# - ${result}`);
        if (
          result.toLowerCase().includes("visible") ||
          result.toLowerCase().includes("displayed")
        ) {
          lines.push(`- assertVisible: "Element"`);
        } else if (result.toLowerCase().includes("text")) {
          lines.push(`- assertVisible: "Expected Text"`);
        }
      });
    }

    lines.push(``);
    lines.push(`---`);
  });

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-${timestamp}.yaml`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/yaml",
  };
}
