// lib/exports/mobile/xcuitest.ts
export function exportToXCUITest(testCases: any[], suiteName: string) {
  const className = suiteName.replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    `//`,
    `// ${suiteName} - XCUITest Suite`,
    `// Generated by SynthQA`,
    `//`,
    ``,
    `import XCTest`,
    ``,
    `class ${className}Tests: XCTestCase {`,
    `    `,
    `    var app: XCUIApplication!`,
    `    `,
    `    override func setUpWithError() throws {`,
    `        continueAfterFailure = false`,
    `        app = XCUIApplication()`,
    `        app.launch()`,
    `    }`,
    `    `,
    `    override func tearDownWithError() throws {`,
    `        app.terminate()`,
    `    }`,
    `    `,
  ];

  testCases.forEach((tc, idx) => {
    const methodName = tc.title
      .split(/\s+/)
      .map((word: string, i: number) =>
        i === 0
          ? word.toLowerCase()
          : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
      )
      .join("")
      .replace(/[^a-zA-Z0-9]/g, "");

    lines.push(
      `    func test${methodName.charAt(0).toUpperCase() + methodName.slice(1)}() throws {`,
    );
    lines.push(`        // ${tc.title}`);

    if (tc.description) {
      lines.push(`        // ${tc.description}`);
    }

    // Preconditions
    if (tc.preconditions && Array.isArray(tc.preconditions)) {
      lines.push(`        // Preconditions:`);
      tc.preconditions.forEach((p: string) => {
        lines.push(`        // - ${p}`);
      });
    }

    lines.push(``);

    // Steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string, stepIdx: number) => {
        lines.push(`        // Step ${stepIdx + 1}: ${step}`);

        if (
          step.toLowerCase().includes("tap") ||
          step.toLowerCase().includes("click")
        ) {
          lines.push(`        app.buttons["buttonIdentifier"].tap()`);
        } else if (
          step.toLowerCase().includes("type") ||
          step.toLowerCase().includes("enter")
        ) {
          lines.push(
            `        let textField = app.textFields["textFieldIdentifier"]`,
          );
          lines.push(`        textField.tap()`);
          lines.push(`        textField.typeText("test value")`);
        } else if (step.toLowerCase().includes("swipe")) {
          if (step.toLowerCase().includes("up")) {
            lines.push(`        app.swipeUp()`);
          } else if (step.toLowerCase().includes("down")) {
            lines.push(`        app.swipeDown()`);
          } else {
            lines.push(`        app.swipeLeft()`);
          }
        } else if (step.toLowerCase().includes("wait")) {
          lines.push(
            `        let element = app.staticTexts["elementIdentifier"]`,
          );
          lines.push(
            `        XCTAssertTrue(element.waitForExistence(timeout: 5))`,
          );
        } else {
          lines.push(`        // TODO: Implement - ${step}`);
        }
        lines.push(``);
      });
    }

    // Expected results
    if (tc.expected_results && Array.isArray(tc.expected_results)) {
      lines.push(`        // Expected results:`);
      tc.expected_results.forEach((result: string) => {
        lines.push(`        // - ${result}`);
        if (
          result.toLowerCase().includes("visible") ||
          result.toLowerCase().includes("exist")
        ) {
          lines.push(
            `        XCTAssertTrue(app.staticTexts["elementIdentifier"].exists)`,
          );
        }
      });
    }

    lines.push(`    }`);
    lines.push(``);
  });

  lines.push(`}`);

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${className}Tests.swift`;

  return {
    content: lines.join("\n"),
    filename,
    mimeType: "text/x-swift",
  };
}
