// lib/exports/accessibility/axe.ts
export function exportToAxe(testCases: any[], suiteName: string) {
  const config = {
    name: suiteName,
    description: "Accessibility test configuration generated by SynthQA",
    rules: [] as any[],
    checks: [] as any[],
    urls: [] as string[],
    runOnly: {
      type: "tag",
      values: ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "best-practice"],
    },
    reporter: "v2",
    resultTypes: ["violations", "incomplete", "passes"],
  };

  // Extract URLs and accessibility checks from test cases
  const seenUrls = new Set<string>();

  testCases.forEach((tc) => {
    // Extract URLs from steps
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string) => {
        const urlMatch = step.match(/https?:\/\/[^\s]+/);
        if (urlMatch && !seenUrls.has(urlMatch[0])) {
          seenUrls.add(urlMatch[0]);
          config.urls.push(urlMatch[0]);
        }
      });
    }

    // Add specific accessibility checks based on test case
    const title = tc.title.toLowerCase();
    const description = (tc.description || "").toLowerCase();
    const combined = title + " " + description;

    if (combined.includes("color contrast")) {
      config.checks.push({
        id: "color-contrast",
        enabled: true,
        options: { noScroll: false },
      });
    }

    if (combined.includes("keyboard") || combined.includes("focus")) {
      config.checks.push({
        id: "focus-order-semantics",
        enabled: true,
      });
    }

    if (combined.includes("screen reader") || combined.includes("aria")) {
      config.checks.push({
        id: "aria-allowed-attr",
        enabled: true,
      });
      config.checks.push({
        id: "aria-required-attr",
        enabled: true,
      });
    }

    if (combined.includes("image") || combined.includes("alt")) {
      config.checks.push({
        id: "image-alt",
        enabled: true,
      });
    }

    if (combined.includes("form") || combined.includes("label")) {
      config.checks.push({
        id: "label",
        enabled: true,
      });
    }

    if (combined.includes("heading")) {
      config.checks.push({
        id: "heading-order",
        enabled: true,
      });
    }
  });

  // Default URLs if none found
  if (config.urls.length === 0) {
    config.urls.push("https://example.com");
  }

  // Add test suite as metadata
  const axeConfig = {
    ...config,
    metadata: {
      generatedBy: "SynthQA",
      suite: suiteName,
      testCount: testCases.length,
      generatedAt: new Date().toISOString(),
    },
    testCases: testCases.map((tc) => ({
      id: tc.id,
      title: tc.title,
      description: tc.description,
      wcagCriteria: extractWCAGCriteria(tc),
    })),
  };

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-axe-${timestamp}.json`;

  return {
    content: JSON.stringify(axeConfig, null, 2),
    filename,
    mimeType: "application/json",
  };
}

function extractWCAGCriteria(tc: any): string[] {
  const criteria: string[] = [];
  const text = `${tc.title} ${tc.description}`.toLowerCase();

  const wcagMap: Record<string, string> = {
    "color contrast": "1.4.3",
    "text alternative": "1.1.1",
    keyboard: "2.1.1",
    focus: "2.4.7",
    heading: "1.3.1",
    "link purpose": "2.4.4",
    "form label": "3.3.2",
    "error identification": "3.3.1",
    "page title": "2.4.2",
    language: "3.1.1",
  };

  for (const [keyword, criterion] of Object.entries(wcagMap)) {
    if (text.includes(keyword)) {
      criteria.push(criterion);
    }
  }

  return criteria.length > 0 ? criteria : ["1.4.3", "2.1.1", "4.1.2"]; // Default WCAG criteria
}
