// lib/exports/accessibility/wave.ts
export function exportToWAVE(testCases: any[], suiteName: string) {
  const urls = new Set<string>();

  testCases.forEach((tc) => {
    if (tc.steps && Array.isArray(tc.steps)) {
      tc.steps.forEach((step: string) => {
        const urlMatch = step.match(/https?:\/\/[^\s]+/);
        if (urlMatch) {
          urls.add(urlMatch[0]);
        }
      });
    }
  });

  const urlList = Array.from(urls);
  if (urlList.length === 0) {
    urlList.push("https://example.com");
  }

  const config = {
    name: suiteName,
    description: "WAVE accessibility test configuration generated by SynthQA",
    apiKey: "YOUR_WAVE_API_KEY", // User must replace
    reportType: "json",
    tests: urlList.map((url) => ({
      url,
      reportType: "4",
      evaluateDelayed: true,
    })),
    testCases: testCases.map((tc) => ({
      id: tc.id,
      title: tc.title,
      description: tc.description,
      checkFor: extractWAVEChecks(tc),
    })),
    metadata: {
      suite: suiteName,
      generatedBy: "SynthQA",
      generatedAt: new Date().toISOString(),
      testCount: testCases.length,
      instructions: [
        "1. Sign up for WAVE API key at https://wave.webaim.org/api/",
        "2. Replace YOUR_WAVE_API_KEY with your actual API key",
        "3. Update URLs to match your application",
        "4. Run WAVE tests using the API or browser extension",
      ],
    },
  };

  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `${suiteName.toLowerCase().replace(/\s+/g, "-")}-wave-${timestamp}.json`;

  return {
    content: JSON.stringify(config, null, 2),
    filename,
    mimeType: "application/json",
  };
}

function extractWAVEChecks(tc: any): string[] {
  const checks: string[] = [];
  const text = `${tc.title} ${tc.description}`.toLowerCase();

  const checkMap: Record<string, string> = {
    "alt text": "Missing alternative text",
    "color contrast": "Low contrast",
    heading: "Heading structure",
    form: "Form label",
    aria: "ARIA usage",
    link: "Link purpose",
    keyboard: "Keyboard accessibility",
    focus: "Focus management",
  };

  for (const [keyword, check] of Object.entries(checkMap)) {
    if (text.includes(keyword)) {
      checks.push(check);
    }
  }

  return checks.length > 0
    ? checks
    : ["Missing alternative text", "Low contrast", "ARIA usage"];
}
